#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.1                         #
#------------------------------------------------------------------------------#


WRKDIR = `pwd`
MAKE = make

all: commonlib_commonlib timekeeper

commonlib_commonlib: 
	$(MAKE) -C CommonLib all -f CommonLib.cbp.mak

timekeeper: 
	$(MAKE) all -f TimeKeeper.cbp.mak

clean: clean_commonlib_commonlib clean_timekeeper

clean_commonlib_commonlib: 
	$(MAKE) -C CommonLib clean -f CommonLib.cbp.mak

clean_timekeeper: 
	$(MAKE) clean -f TimeKeeper.cbp.mak

.PHONY: clean_commonlib_commonlib clean_timekeeper

